/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinic;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jimma University
 */
public class uncompleted extends javax.swing.JPanel {

    /**
     * Creates new form pp
     */
    private String stid,date;
    OPD1 opd;
    

    public uncompleted(String id, String name, String date, OPD1 opd) {
        initComponents();
        this.opd = opd;
        waiting_pt_mrn.setText(id);
        waiting_pt.setText(name);
        String[] st = name.split(" ");
        this.date = date;
        this.stid = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_holder = new javax.swing.JPanel();
        waiting_pt = new javax.swing.JLabel();
        mrn_holder = new javax.swing.JPanel();
        waiting_pt_mrn = new javax.swing.JLabel();
        call1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(360, 12));

        name_holder.setBackground(new java.awt.Color(255, 255, 255));

        waiting_pt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        waiting_pt.setText("jLabel1");

        javax.swing.GroupLayout name_holderLayout = new javax.swing.GroupLayout(name_holder);
        name_holder.setLayout(name_holderLayout);
        name_holderLayout.setHorizontalGroup(
            name_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waiting_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        name_holderLayout.setVerticalGroup(
            name_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waiting_pt)
                .addContainerGap())
        );

        mrn_holder.setBackground(new java.awt.Color(255, 255, 255));

        waiting_pt_mrn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        waiting_pt_mrn.setText("jLabel1");

        javax.swing.GroupLayout mrn_holderLayout = new javax.swing.GroupLayout(mrn_holder);
        mrn_holder.setLayout(mrn_holderLayout);
        mrn_holderLayout.setHorizontalGroup(
            mrn_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrn_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waiting_pt_mrn, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        mrn_holderLayout.setVerticalGroup(
            mrn_holderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrn_holderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waiting_pt_mrn)
                .addContainerGap())
        );

        call1.setBackground(new java.awt.Color(0, 102, 204));
        call1.setText("Open");
        call1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mrn_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(call1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(call1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mrn_holder, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(name_holder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void call1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call1ActionPerformed
        // TODO add your handling code here:
//        opd.saveHistory(1);
        System.out.println("sending........."+date+" .... "+stid);
        try {
            opd.load_uncompleted(date, stid);
        } catch (SQLException ex) {
            Logger.getLogger(uncompleted.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_call1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton call1;
    private javax.swing.JPanel mrn_holder;
    private javax.swing.JPanel name_holder;
    private javax.swing.JLabel waiting_pt;
    private javax.swing.JLabel waiting_pt_mrn;
    // End of variables declaration//GEN-END:variables

    
}
